name: C++ Compile Test

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Install C++ Compiler
      run: |
        sudo apt-get update
        sudo apt-get install g++-4.8 -y
        sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90

    - name: Compile Code
      run: |
        make
