name: C++ Compile Test

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Install C++ Compiler
      run: |
        sudo apt-get update
        sudo apt-get install g++ -y

    - name: Compile Code
      run: |
        make
