name: C++ Compile Test

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Install C++ Compiler
      run: |
        sudo apt-get update
        sudo apt-get install g++ -y

    - name: Compile Files Excluding Specific Headers
      run: |
        find . -name '*.cpp' ! -exec grep -q '<sys/event.h>' {} \; ! -exec grep -q '"./core/Kqueue.hpp"' {} \; -print | while read file; do
          g++ -Wall -Werror -Wextra -std=c++98 -c "$file" -o "${file%.cpp}.o"
        done
